title: sward
description: blog & landing page
baseurl: "/home"
url: "https://swardforever.github.io"

markdown: kramdown
kramdown:
  math engine: null
permalink: /blog/:year/:month/:day/:title/

exclude:
  - README.md
  - node_modules
  - vendor
  - .git
